# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ebalo/Scrivania/Projects/c++/TD-TowerDefense-SFML

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ebalo/Scrivania/Projects/c++/TD-TowerDefense-SFML

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ebalo/Scrivania/Projects/c++/TD-TowerDefense-SFML/CMakeFiles /home/ebalo/Scrivania/Projects/c++/TD-TowerDefense-SFML/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ebalo/Scrivania/Projects/c++/TD-TowerDefense-SFML/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TD_TowerDefense_SFML_Tests

# Build rule for target.
TD_TowerDefense_SFML_Tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TD_TowerDefense_SFML_Tests
.PHONY : TD_TowerDefense_SFML_Tests

# fast build rule for target.
TD_TowerDefense_SFML_Tests/fast:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build
.PHONY : TD_TowerDefense_SFML_Tests/fast

#=============================================================================
# Target rules for targets named TD_TowerDefense_SFML

# Build rule for target.
TD_TowerDefense_SFML: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TD_TowerDefense_SFML
.PHONY : TD_TowerDefense_SFML

# fast build rule for target.
TD_TowerDefense_SFML/fast:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/build
.PHONY : TD_TowerDefense_SFML/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f Tests/CMakeFiles/test.dir/build.make Tests/CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f Tests/googletest/CMakeFiles/gtest_main.dir/build.make Tests/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f Tests/googletest/CMakeFiles/gtest.dir/build.make Tests/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

Classes/Elements/ButtonIcon.o: Classes/Elements/ButtonIcon.cpp.o

.PHONY : Classes/Elements/ButtonIcon.o

# target to build an object file
Classes/Elements/ButtonIcon.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/ButtonIcon.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/ButtonIcon.cpp.o
.PHONY : Classes/Elements/ButtonIcon.cpp.o

Classes/Elements/ButtonIcon.i: Classes/Elements/ButtonIcon.cpp.i

.PHONY : Classes/Elements/ButtonIcon.i

# target to preprocess a source file
Classes/Elements/ButtonIcon.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/ButtonIcon.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/ButtonIcon.cpp.i
.PHONY : Classes/Elements/ButtonIcon.cpp.i

Classes/Elements/ButtonIcon.s: Classes/Elements/ButtonIcon.cpp.s

.PHONY : Classes/Elements/ButtonIcon.s

# target to generate assembly for a file
Classes/Elements/ButtonIcon.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/ButtonIcon.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/ButtonIcon.cpp.s
.PHONY : Classes/Elements/ButtonIcon.cpp.s

Classes/Elements/ButtonRect.o: Classes/Elements/ButtonRect.cpp.o

.PHONY : Classes/Elements/ButtonRect.o

# target to build an object file
Classes/Elements/ButtonRect.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/ButtonRect.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/ButtonRect.cpp.o
.PHONY : Classes/Elements/ButtonRect.cpp.o

Classes/Elements/ButtonRect.i: Classes/Elements/ButtonRect.cpp.i

.PHONY : Classes/Elements/ButtonRect.i

# target to preprocess a source file
Classes/Elements/ButtonRect.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/ButtonRect.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/ButtonRect.cpp.i
.PHONY : Classes/Elements/ButtonRect.cpp.i

Classes/Elements/ButtonRect.s: Classes/Elements/ButtonRect.cpp.s

.PHONY : Classes/Elements/ButtonRect.s

# target to generate assembly for a file
Classes/Elements/ButtonRect.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/ButtonRect.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/ButtonRect.cpp.s
.PHONY : Classes/Elements/ButtonRect.cpp.s

Classes/Elements/DrawableFactory.o: Classes/Elements/DrawableFactory.cpp.o

.PHONY : Classes/Elements/DrawableFactory.o

# target to build an object file
Classes/Elements/DrawableFactory.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/DrawableFactory.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/DrawableFactory.cpp.o
.PHONY : Classes/Elements/DrawableFactory.cpp.o

Classes/Elements/DrawableFactory.i: Classes/Elements/DrawableFactory.cpp.i

.PHONY : Classes/Elements/DrawableFactory.i

# target to preprocess a source file
Classes/Elements/DrawableFactory.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/DrawableFactory.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/DrawableFactory.cpp.i
.PHONY : Classes/Elements/DrawableFactory.cpp.i

Classes/Elements/DrawableFactory.s: Classes/Elements/DrawableFactory.cpp.s

.PHONY : Classes/Elements/DrawableFactory.s

# target to generate assembly for a file
Classes/Elements/DrawableFactory.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/DrawableFactory.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/DrawableFactory.cpp.s
.PHONY : Classes/Elements/DrawableFactory.cpp.s

Classes/Elements/Enemy.o: Classes/Elements/Enemy.cpp.o

.PHONY : Classes/Elements/Enemy.o

# target to build an object file
Classes/Elements/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Enemy.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Enemy.cpp.o
.PHONY : Classes/Elements/Enemy.cpp.o

Classes/Elements/Enemy.i: Classes/Elements/Enemy.cpp.i

.PHONY : Classes/Elements/Enemy.i

# target to preprocess a source file
Classes/Elements/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Enemy.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Enemy.cpp.i
.PHONY : Classes/Elements/Enemy.cpp.i

Classes/Elements/Enemy.s: Classes/Elements/Enemy.cpp.s

.PHONY : Classes/Elements/Enemy.s

# target to generate assembly for a file
Classes/Elements/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Enemy.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Enemy.cpp.s
.PHONY : Classes/Elements/Enemy.cpp.s

Classes/Elements/EnemyGenerator.o: Classes/Elements/EnemyGenerator.cpp.o

.PHONY : Classes/Elements/EnemyGenerator.o

# target to build an object file
Classes/Elements/EnemyGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/EnemyGenerator.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/EnemyGenerator.cpp.o
.PHONY : Classes/Elements/EnemyGenerator.cpp.o

Classes/Elements/EnemyGenerator.i: Classes/Elements/EnemyGenerator.cpp.i

.PHONY : Classes/Elements/EnemyGenerator.i

# target to preprocess a source file
Classes/Elements/EnemyGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/EnemyGenerator.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/EnemyGenerator.cpp.i
.PHONY : Classes/Elements/EnemyGenerator.cpp.i

Classes/Elements/EnemyGenerator.s: Classes/Elements/EnemyGenerator.cpp.s

.PHONY : Classes/Elements/EnemyGenerator.s

# target to generate assembly for a file
Classes/Elements/EnemyGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/EnemyGenerator.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/EnemyGenerator.cpp.s
.PHONY : Classes/Elements/EnemyGenerator.cpp.s

Classes/Elements/Tower.o: Classes/Elements/Tower.cpp.o

.PHONY : Classes/Elements/Tower.o

# target to build an object file
Classes/Elements/Tower.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Tower.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Tower.cpp.o
.PHONY : Classes/Elements/Tower.cpp.o

Classes/Elements/Tower.i: Classes/Elements/Tower.cpp.i

.PHONY : Classes/Elements/Tower.i

# target to preprocess a source file
Classes/Elements/Tower.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Tower.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Tower.cpp.i
.PHONY : Classes/Elements/Tower.cpp.i

Classes/Elements/Tower.s: Classes/Elements/Tower.cpp.s

.PHONY : Classes/Elements/Tower.s

# target to generate assembly for a file
Classes/Elements/Tower.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Tower.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Tower.cpp.s
.PHONY : Classes/Elements/Tower.cpp.s

Classes/Elements/Turret.o: Classes/Elements/Turret.cpp.o

.PHONY : Classes/Elements/Turret.o

# target to build an object file
Classes/Elements/Turret.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Turret.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Turret.cpp.o
.PHONY : Classes/Elements/Turret.cpp.o

Classes/Elements/Turret.i: Classes/Elements/Turret.cpp.i

.PHONY : Classes/Elements/Turret.i

# target to preprocess a source file
Classes/Elements/Turret.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Turret.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Turret.cpp.i
.PHONY : Classes/Elements/Turret.cpp.i

Classes/Elements/Turret.s: Classes/Elements/Turret.cpp.s

.PHONY : Classes/Elements/Turret.s

# target to generate assembly for a file
Classes/Elements/Turret.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/Turret.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/Turret.cpp.s
.PHONY : Classes/Elements/Turret.cpp.s

Classes/Elements/TurretGenerator.o: Classes/Elements/TurretGenerator.cpp.o

.PHONY : Classes/Elements/TurretGenerator.o

# target to build an object file
Classes/Elements/TurretGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/TurretGenerator.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/TurretGenerator.cpp.o
.PHONY : Classes/Elements/TurretGenerator.cpp.o

Classes/Elements/TurretGenerator.i: Classes/Elements/TurretGenerator.cpp.i

.PHONY : Classes/Elements/TurretGenerator.i

# target to preprocess a source file
Classes/Elements/TurretGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/TurretGenerator.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/TurretGenerator.cpp.i
.PHONY : Classes/Elements/TurretGenerator.cpp.i

Classes/Elements/TurretGenerator.s: Classes/Elements/TurretGenerator.cpp.s

.PHONY : Classes/Elements/TurretGenerator.s

# target to generate assembly for a file
Classes/Elements/TurretGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Elements/TurretGenerator.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Elements/TurretGenerator.cpp.s
.PHONY : Classes/Elements/TurretGenerator.cpp.s

Classes/EventHandler.o: Classes/EventHandler.cpp.o

.PHONY : Classes/EventHandler.o

# target to build an object file
Classes/EventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/EventHandler.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/EventHandler.cpp.o
.PHONY : Classes/EventHandler.cpp.o

Classes/EventHandler.i: Classes/EventHandler.cpp.i

.PHONY : Classes/EventHandler.i

# target to preprocess a source file
Classes/EventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/EventHandler.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/EventHandler.cpp.i
.PHONY : Classes/EventHandler.cpp.i

Classes/EventHandler.s: Classes/EventHandler.cpp.s

.PHONY : Classes/EventHandler.s

# target to generate assembly for a file
Classes/EventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/EventHandler.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/EventHandler.cpp.s
.PHONY : Classes/EventHandler.cpp.s

Classes/Maps/AssetsMap.o: Classes/Maps/AssetsMap.cpp.o

.PHONY : Classes/Maps/AssetsMap.o

# target to build an object file
Classes/Maps/AssetsMap.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Maps/AssetsMap.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Maps/AssetsMap.cpp.o
.PHONY : Classes/Maps/AssetsMap.cpp.o

Classes/Maps/AssetsMap.i: Classes/Maps/AssetsMap.cpp.i

.PHONY : Classes/Maps/AssetsMap.i

# target to preprocess a source file
Classes/Maps/AssetsMap.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Maps/AssetsMap.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Maps/AssetsMap.cpp.i
.PHONY : Classes/Maps/AssetsMap.cpp.i

Classes/Maps/AssetsMap.s: Classes/Maps/AssetsMap.cpp.s

.PHONY : Classes/Maps/AssetsMap.s

# target to generate assembly for a file
Classes/Maps/AssetsMap.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Maps/AssetsMap.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Maps/AssetsMap.cpp.s
.PHONY : Classes/Maps/AssetsMap.cpp.s

Classes/Maps/RenderableMap.o: Classes/Maps/RenderableMap.cpp.o

.PHONY : Classes/Maps/RenderableMap.o

# target to build an object file
Classes/Maps/RenderableMap.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Maps/RenderableMap.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Maps/RenderableMap.cpp.o
.PHONY : Classes/Maps/RenderableMap.cpp.o

Classes/Maps/RenderableMap.i: Classes/Maps/RenderableMap.cpp.i

.PHONY : Classes/Maps/RenderableMap.i

# target to preprocess a source file
Classes/Maps/RenderableMap.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Maps/RenderableMap.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Maps/RenderableMap.cpp.i
.PHONY : Classes/Maps/RenderableMap.cpp.i

Classes/Maps/RenderableMap.s: Classes/Maps/RenderableMap.cpp.s

.PHONY : Classes/Maps/RenderableMap.s

# target to generate assembly for a file
Classes/Maps/RenderableMap.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/Maps/RenderableMap.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/Maps/RenderableMap.cpp.s
.PHONY : Classes/Maps/RenderableMap.cpp.s

Classes/RenderHandler.o: Classes/RenderHandler.cpp.o

.PHONY : Classes/RenderHandler.o

# target to build an object file
Classes/RenderHandler.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/RenderHandler.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/RenderHandler.cpp.o
.PHONY : Classes/RenderHandler.cpp.o

Classes/RenderHandler.i: Classes/RenderHandler.cpp.i

.PHONY : Classes/RenderHandler.i

# target to preprocess a source file
Classes/RenderHandler.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/RenderHandler.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/RenderHandler.cpp.i
.PHONY : Classes/RenderHandler.cpp.i

Classes/RenderHandler.s: Classes/RenderHandler.cpp.s

.PHONY : Classes/RenderHandler.s

# target to generate assembly for a file
Classes/RenderHandler.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/Classes/RenderHandler.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/Classes/RenderHandler.cpp.s
.PHONY : Classes/RenderHandler.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML_Tests.dir/build.make CMakeFiles/TD_TowerDefense_SFML_Tests.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/TD_TowerDefense_SFML.dir/build.make CMakeFiles/TD_TowerDefense_SFML.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TD_TowerDefense_SFML_Tests"
	@echo "... TD_TowerDefense_SFML"
	@echo "... test"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... Classes/Elements/ButtonIcon.o"
	@echo "... Classes/Elements/ButtonIcon.i"
	@echo "... Classes/Elements/ButtonIcon.s"
	@echo "... Classes/Elements/ButtonRect.o"
	@echo "... Classes/Elements/ButtonRect.i"
	@echo "... Classes/Elements/ButtonRect.s"
	@echo "... Classes/Elements/DrawableFactory.o"
	@echo "... Classes/Elements/DrawableFactory.i"
	@echo "... Classes/Elements/DrawableFactory.s"
	@echo "... Classes/Elements/Enemy.o"
	@echo "... Classes/Elements/Enemy.i"
	@echo "... Classes/Elements/Enemy.s"
	@echo "... Classes/Elements/EnemyGenerator.o"
	@echo "... Classes/Elements/EnemyGenerator.i"
	@echo "... Classes/Elements/EnemyGenerator.s"
	@echo "... Classes/Elements/Tower.o"
	@echo "... Classes/Elements/Tower.i"
	@echo "... Classes/Elements/Tower.s"
	@echo "... Classes/Elements/Turret.o"
	@echo "... Classes/Elements/Turret.i"
	@echo "... Classes/Elements/Turret.s"
	@echo "... Classes/Elements/TurretGenerator.o"
	@echo "... Classes/Elements/TurretGenerator.i"
	@echo "... Classes/Elements/TurretGenerator.s"
	@echo "... Classes/EventHandler.o"
	@echo "... Classes/EventHandler.i"
	@echo "... Classes/EventHandler.s"
	@echo "... Classes/Maps/AssetsMap.o"
	@echo "... Classes/Maps/AssetsMap.i"
	@echo "... Classes/Maps/AssetsMap.s"
	@echo "... Classes/Maps/RenderableMap.o"
	@echo "... Classes/Maps/RenderableMap.i"
	@echo "... Classes/Maps/RenderableMap.s"
	@echo "... Classes/RenderHandler.o"
	@echo "... Classes/RenderHandler.i"
	@echo "... Classes/RenderHandler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

