//
// Created by ebalo on 10/03/20.
//

#ifndef TD_TOWERDEFENSE_SFML_DIFFICULTSTATE_H
#define TD_TOWERDEFENSE_SFML_DIFFICULTSTATE_H

enum DIFFICULT_STATE {
    easy,
    hard,
    hacked
};

#endif //TD_TOWERDEFENSE_SFML_DIFFICULTSTATE_H
