//
// Created by ebalo on 16/03/20.
//

#ifndef TD_TOWERDEFENSE_WINDOWSIZE_H
#define TD_TOWERDEFENSE_WINDOWSIZE_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 800

#endif //TD_TOWERDEFENSE_WINDOWSIZE_H
